[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
polyguard_market = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
polyguard_orderbook = "HmbTLCmaGvZhKnn1Zfa1JVnp7vkMV4DYVxPLWBVoN65L"
polyguard_privacy = "Eo4XoY6cHmQbPr9S1K7fUhbELeHBP4qkfUHJp2Ht8rQm"

[programs.devnet]
polyguard_market = "98jqxMe88XGjXzCY3bwV1Kuqzj32fcwdhPZa193RUffQ"
polyguard_orderbook = "59LqZtVU2YBrhv8B2E1iASJMzcyBHWhY2JuaJsCXkAS8"
polyguard_privacy = "9QGtHZJvmjMKTME1s3mVfNXtGpEdXDQZJTxsxqve9GsL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
